"use strict";
const { contextBridge, ipcRenderer } = require('electron');
console.log('[Preload] Initializing electronAPI...');
contextBridge.exposeInMainWorld('electronAPI', {
    isFirstLaunch: () => ipcRenderer.invoke('is-first-launch'),
    markAsLaunched: () => ipcRenderer.invoke('mark-as-launched'),
    getAccounts: () => ipcRenderer.invoke('get-accounts'),
    getActiveAccount: () => ipcRenderer.invoke('get-active-account'),
    setActiveAccount: (accountId) => ipcRenderer.invoke('set-active-account', accountId),
    removeAccount: (accountId) => ipcRenderer.invoke('remove-account', accountId),
    startHytaleOAuth: () => ipcRenderer.invoke('start-hytale-oauth'),
    pollOAuthToken: () => ipcRenderer.invoke('poll-oauth-token'),
    cancelOAuth: () => ipcRenderer.invoke('cancel-oauth'),
    refreshAccountToken: (accountId) => ipcRenderer.invoke('refresh-account-token', accountId),
    initiateHytaleLogin: () => ipcRenderer.invoke('initiate-hytale-login'),
    confirmHytaleAccount: (username) => ipcRenderer.invoke('confirm-hytale-account', username),
    addOfflineAccount: (username) => ipcRenderer.invoke('add-offline-account', username),
    launchGame: (instanceId) => ipcRenderer.invoke('launch-game', instanceId),
    isGameInstalled: () => ipcRenderer.invoke('is-game-installed'),
    getGameDir: () => ipcRenderer.invoke('get-game-dir'),
    getLatestVersion: () => ipcRenderer.invoke('get-latest-version'),
    getInstalledVersion: () => ipcRenderer.invoke('get-installed-version'),
    setGamePath: (path) => ipcRenderer.invoke('set-game-path', path),
    selectGameFolder: () => ipcRenderer.invoke('select-game-folder'),
    onLaunchProgress: (callback) => ipcRenderer.on('launch-progress', callback),
    getInstances: () => ipcRenderer.invoke('get-instances'),
    createInstance: (name, version, options) => ipcRenderer.invoke('create-instance', name, version, options),
    updateInstance: (id, updates) => ipcRenderer.invoke('update-instance', id, updates),
    deleteInstance: (id) => ipcRenderer.invoke('delete-instance', id),
    openInstanceFolder: (id) => ipcRenderer.invoke('open-instance-folder', id),
    createComplexInstance: (payload) => ipcRenderer.invoke('create-complex-instance', payload),
    copyInstanceMods: (sourceId, targetId, modFiles) => ipcRenderer.invoke('copy-instance-mods', sourceId, targetId, modFiles),
    getInstanceWorlds: (instanceId) => ipcRenderer.invoke('get-instance-worlds', instanceId),
    deleteInstanceWorld: (instanceId, worldName) => ipcRenderer.invoke('delete-instance-world', instanceId, worldName),
    openWorldFolder: (instanceId, worldName) => ipcRenderer.invoke('open-world-folder', instanceId, worldName),
    getSessionTokens: () => ipcRenderer.invoke('get-session-tokens'),
    openExternal: (url) => ipcRenderer.invoke('open-external', url),
    minimizeWindow: () => ipcRenderer.send('minimize-window'),
    closeWindow: () => ipcRenderer.send('close-window'),
    resizeWindow: (width, height) => ipcRenderer.send('resize-window', width, height),
    getHytaleNews: () => ipcRenderer.invoke('get-hytale-news'),
    searchMods: (source, query, filters) => ipcRenderer.invoke('search-mods', source, query, filters),
    installMod: (instanceId, mod) => ipcRenderer.invoke('install-mod', instanceId, mod),
    cancelModWatch: () => ipcRenderer.invoke('cancel-mod-watch'),
    onModInstalled: (callback) => ipcRenderer.on('mod-installed', callback),
    removeModInstalledListener: () => ipcRenderer.removeAllListeners('mod-installed'),
    getInstalledMods: () => ipcRenderer.invoke('get-installed-mods'),
    markModInstalled: (mod, instanceId) => ipcRenderer.invoke('mark-mod-installed', mod, instanceId),
    unmarkModInstalled: (modId, instanceId) => ipcRenderer.invoke('unmark-mod-installed', modId, instanceId),
    getInstanceMods: (instanceId) => ipcRenderer.invoke('get-instance-mods', instanceId),
    removeInstanceMod: (instanceId, fileName, modId) => ipcRenderer.invoke('remove-instance-mod', instanceId, fileName, modId),
    batchInstallMods: (instanceId, mods) => ipcRenderer.invoke('batch-install-mods', instanceId, mods),
    getInstanceServerConfig: (instanceId) => ipcRenderer.invoke('get-instance-server-config', instanceId),
    updateInstanceServerConfig: (instanceId, updates) => ipcRenderer.invoke('update-instance-server-config', instanceId, updates),
    invoke: (channel, ...args) => ipcRenderer.invoke(channel, ...args),
    secureSet: (key, value) => ipcRenderer.invoke('secure-set', key, value),
    secureGet: (key) => ipcRenderer.invoke('secure-get', key),
    onAppClosing: (callback) => {
        ipcRenderer.on('app-closing', () => {
            console.log('[Preload] App closing signal received');
            callback();
        });
    },
    login: (credentials) => ipcRenderer.invoke('login', credentials),
});